{% set name = "apache-flink" %}
{% set version = "1.20.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache-flink-{{ version }}.tar.gz
  sha256: 89ef7758728cd69b06ecb44929a14afe43c3f69682411cdbb822fe5d31465abb

build:
  skip: true  # [py<37 or py>311 or win]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - apache-beam <2.49.0,>=2.43.0
    - python
    - cython
    - pip
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - apache-beam <2.49.0,>=2.43.0
    - python
    - cython
    - pip
  run:
    - apache-beam <2.49.0,>=2.43.0
    - python
    - py4j ==0.10.9.7
    - pemja ==0.4.1
    - python-dateutil <3,>=2.8.0
    - cloudpickle >=2.2.0
    - avro-python3 !=1.9.2,>=1.8.1
    - pytz >=2018.3
    - fastavro !=1.8.0,>=1.1.0
    - requests >=2.26.0
    - protobuf >=3.19.0
    - numpy >=1.22.4
    - pandas >=1.3.0
    - pyarrow >=5.0.0
    - httplib2 >=0.19.0
    - apache-flink-libraries =={{ version }}

test:
  imports:
    - pyflink
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://flink.apache.org
  summary: Apache Flink Python API
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gforsyth
    - deepyaman
    - dianfu
