{% set name = "apache-flink" %}
{% set version = "2.3.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 47ded5aea434b4b6db3e010cbd6893afcde3eda36cbb07e0260f868f56d370f7

build:
  skip: true  # [py<37 or py>311 or win]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - apache-beam <2.61.0,>=2.54.0
    - cython
    - pip
    - python
    - setuptools >=75.3
    - wheel
  host:
    - apache-beam <2.61.0,>=2.54.0
    - cython
    - pip
    - python
    - setuptools >=75.3
    - wheel
  run:
    - apache-beam <2.61.0,>=2.54.0
    - apache-flink-libraries =={{ version }}
    - avro >=1.12.0
    - cloudpickle >=2.2.0
    - fastavro !=1.8.0,>=1.1.0
    - httplib2 >=0.19.0
    - numpy >=1.22.4
    - pandas >=1.3.0
    - pemja ==0.5.2
    - protobuf >=3.19.0
    - py4j ==0.10.9.7
    - pyarrow >=5.0.0
    - python
    - python-dateutil <3,>=2.8.0
    - pytz >=2018.3
    - requests >=2.26.0
    - ruamel.yaml >=0.18.4

test:
  imports:
    - pyflink
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://flink.apache.org
  summary: Apache Flink Python API
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gforsyth
    - deepyaman
    - dianfu
